bandohq/react-bando

src/components/Footer/index.test.tsx, src/components/Navbar/index.test.tsx, src/components/SimpleFooter/index.test.tsx, src/components/forms/GetQuoteForm/index.test.tsx, src/components/forms/RampForm/index.test.tsx, src/hooks/useTransaction/index.test.tsx, tsconfig.json
- simple footer tests
- footer tests
- fix tests pt 1
- fix tests pt 2
=> CHORE - Add footer tests.

src/components/forms/KycForm/index.tsx
=> CHORE - Handle different kinds of KYC errors from the backend.

.gitignore, src/components/forms/GetQuoteForm/index.tsx, src/components/forms/Select/index.tsx, src/layouts/LandingLayout/index.tsx
=> FIX - Tweaks to main widget on small screens.

src/components/UserMenu/index.tsx, src/components/forms/Select/index.tsx, src/config/constants/currencies.tsx, src/hooks/useUser/MagicUserProvider.tsx, src/hooks/useUser/index.tsx, src/hooks/useUser/requests.ts, src/pages/SignIn/index.tsx
- Correctly fetch user data after login
- Remove user data on logout
=> FIX: Bug where login state was not updated when login in/out

package.json, src/components/KycBulletPoints/index.tsx, src/components/SimpleFooter/index.test.tsx, src/components/SimpleFooter/index.tsx, src/components/TransactionDetails/index.tsx, src/components/UserMenu/index.tsx, src/components/forms/RampForm/index.test.tsx, src/components/forms/RampForm/index.tsx, src/components/forms/Select/index.tsx, src/config/constants/links.ts, src/helpers/TestProvider.tsx, src/index.css, src/layouts/CleanLayout/index.tsx, src/pages/ProtectedTransactionDetail/index.tsx, src/pages/TransactionDetail/index.tsx, src/routes/index.tsx, src/translations/es/faq.ts, src/translations/es/index.ts, src/translations/es/kycPoints.ts, src/translations/es/ramp.ts, src/translations/es/transactionDetail.ts, src/translations/es/userMenu.ts, yarn.lock
- Adds CTA buttons for the transaction details screen
- Move some strings to translation files
=> task: Add transaction details CTA buttons & some translations

src/components/forms/RampForm/index.tsx, src/translations/es/ramp.ts
Simple errorbox container on txns errors and user limit errors.
=> CHORE - Simple error message for limits and txns

src/components/forms/RampForm/index.tsx, src/translations/es/ramp.ts
depends on bandohq/core-modules#39
=> CHORE - HANDLE 406 unacceptable code on recipient.

src/components/TransactionDetails/index.tsx, src/components/TransactionDetails/mapProviderStatus.ts, src/components/forms/RampForm/RampTitle.tsx
=> CHORE - Add some info text on expired and failed transactions

src/hooks/useTransaction/requests.ts, src/translations/es/ramp.ts
- **remove front end workaround, fix copy in error mesage**
- **remove front end workaround, fix copy in error mesage**
=> CHORE - Remove work around that has been fixed on the backend

src/translations/en/faq.ts, src/translations/en/index.ts, src/translations/en/kycPoints.ts, src/translations/en/landing.ts, src/translations/en/ramp.ts, src/translations/en/transactionDetail.ts, src/translations/en/transactions.ts, src/translations/en/userMenu.ts
Added english support to the translations folder
=> Added english language dictionary to translations folder

src/translations/en/faq.ts, src/translations/en/landing.ts
=> Quick fix for some typos

src/components/forms/GetQuoteForm/index.tsx, src/components/forms/GetQuoteForm/schema.ts, src/components/forms/Input/index.tsx, src/translations/en/form.ts, src/translations/en/index.ts, src/translations/es/form.ts, src/translations/es/index.ts
=> FIX - Minimum amounts on quote

src/components/forms/GetQuoteForm/schema.ts
=> CHORE - Quote max amounts

src/assets/TokenPlaceholderGray.svg, src/components/TokensWidget/components.tsx, src/components/TokensWidget/index.tsx, src/components/TransactionsTable/CellDetailWithIcon.tsx, src/components/forms/GetQuoteForm/index.tsx, src/components/forms/GetQuoteForm/schema.ts, src/components/forms/GetQuoteForm/v2/index.tsx, src/config/constants/currencies.tsx, src/hooks/useNetworks/requests.ts, src/hooks/useTokens/index.test.tsx, src/hooks/useTokens/index.ts, src/hooks/useTokens/requests.ts, src/hooks/useTransaction/requests.ts, src/pages/Landing/index.tsx
- Switch form values for networks
- Dinamically show network image & currency image
- Hardcode data until selection drawer is ready
=> task: Hook component & switch networks

src/components/TransactionDetails/index.tsx, src/components/forms/RampForm/CurrencyPill.tsx, src/config/constants/currencies.tsx
=> FIX - Mobile tweaks on details PT1

src/components/StatusBadge/index.tsx, src/components/TransactionDetails/index.tsx
Status Badges:
Deposit Details:
=> FIX - Mobile tweaks on details Pt2

src/translations/es/landing.ts
- updates on the landing page text
=> Cambios en wording de la landing

src/config/constants/networks.ts
-5634-49f5-93c4-cea532e43faf">
=> CHORE - Enable scroll

src/components/TokensWidget/NetworkTiles.tsx, src/components/TokensWidget/TokensList.tsx, src/components/forms/GetQuoteForm/v2/index.tsx, src/hooks/useTokens/index.ts
- Reset tokens search when erasing data
- Fix the display of multiple networks
=> task: Fix network lenght and token search

src/layouts/LandingLayout/index.tsx, src/translations/en/landing.ts, src/translations/es/landing.ts
- **Add Bando lalo video**
- **Add Bando lalo video 2**
=> CHORE - Add video to landing page.

src/components/Footer/index.tsx, src/components/SimpleFooter/index.tsx, src/components/TokensWidget/TokensList.tsx, src/components/TokensWidget/components.tsx, src/components/TokensWidget/index.tsx, src/components/forms/GetQuoteForm/v2/index.tsx, src/config/theme.ts, src/hooks/useQuote/index.tsx, src/index.css, src/layouts/CleanLayout/index.tsx
Address review feedback:
- When having a quote, but changing token, reset the quote
- Do not allow form submission if min/max allowance errors are present
- Make token scroll space bigger
- Make quote format allow from 2-18 decimals
- Add the token address on the list on hover and link it to: https://etherscan.io/address
=> CHORE: Address widget feedback

src/components/TokensWidget/NetworkTiles.tsx, src/components/TokensWidget/TokensList.tsx, src/components/TokensWidget/index.tsx
- Do not disabled search input when there are no results
- Limit network list to one line
- Reset quoted quantity on token chane
- Link explorer url for token address
=> CHORE: Address feedback for widget

src/components/forms/KycForm/index.tsx, src/components/forms/KycForm/schema.ts, src/components/forms/PlacesAutocomplete/index.tsx, src/hooks/useKyc/index.test.tsx, src/hooks/useKyc/requests.ts
- Add Places Autocomplete to KYC form back to improve UX
- Let user submit without filling in autocomplete
=> task: Add autocomplete to KYC form

src/config/constants/currencies.tsx, src/config/constants/networks.ts
- **re-enable mpETH**
- **re-enable-eth**
=> CHORE - Re-enable mpETH

src/components/TokensWidget/NetworkTiles.tsx, src/components/TokensWidget/index.tsx, src/components/TransactionDetails/index.tsx, src/components/forms/GetQuoteForm/v2/index.tsx
- Get quote data on form submit or on blur
- If backend sends allowance are not met, prevent form from advancing to ramp
=> task: Get quote on blur or on submission

src/components/forms/ErrorBox/index.tsx, src/components/forms/RampForm/index.tsx, src/translations/en/ramp.ts, src/translations/es/ramp.ts
=> CHORE - Change limit topup notice to add instructions

src/components/forms/GetQuoteForm/schema.ts, src/components/forms/GetQuoteForm/v2/index.tsx
- **compare allowance on base amount for off ramps.**
- **compare allowance on base amount for off ramps 2**
=> FIX - Max amounts on off ramps

src/hooks/useQuote/requests.ts
=> FIX - Remove Quote Authn

src/components/TokensWidget/NetworkTiles.tsx, src/components/TokensWidget/index.tsx, src/hooks/useNetworks/index.tsx, src/hooks/useNetworks/requests.ts
=> CHORE - Hide inactive networks pt2: Consume direction param on widget

src/components/TokensWidget/index.tsx, src/components/forms/GetQuoteForm/v2/index.tsx
=> CHORE - Set the token selection as the first input field on quotes.

src/layouts/LandingLayout/index.tsx
This fix solve the alignment for the second section (visible) #168
=> FIX: Element misalignment

src/components/Alert/index.tsx, src/components/TokensWidget/alerts.tsx, src/components/TokensWidget/index.tsx, src/components/forms/GetQuoteForm/v2/index.tsx, src/translations/en/quote.ts, src/translations/es/quote.ts
=> CHORE - Add not found route message pt2: Support alert component

src/components/forms/RampForm/index.tsx, src/hooks/useTransaction/requests.ts
Consumes affiliate conversion amounts in USD after requesting  ramp.
=> FIX - Referrals pt3: Consume conversion amount in USD

src/translations/es/footer.ts
=> correccion de typo

src/components/forms/GetQuoteForm/v2/index.tsx, src/layouts/CleanLayout/index.tsx, src/pages/Landing/index.tsx, src/pages/Ramp/index.tsx
=> CHORE - Change landing to clean layouts

src/components/LimitUsage/index.tsx, src/components/UserCard/index.tsx, src/components/UserMenu/index.tsx, src/components/forms/GetQuoteForm/v2/index.tsx, src/components/forms/KycForm/index.tsx, src/components/forms/RampForm/index.tsx, src/translations/en/userMenu.ts, src/translations/es/userMenu.ts
=> CHORE - Pending account alerts

src/pages/PrivacyNotice/index.tsx, src/pages/Terms/index.tsx, src/routes/index.tsx
Privacy notice page, and new terms in english.
=> CHORE - New terms and privacy notice
